#!/bin/bash

# Set up pathogen
/bin/mkdir -p ~/.vim/autoload ~/.vim/bundle
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# Set up NERDTree
cd ~/.vim/bundle
/usr/bin/git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree

# Set up vim-airline
/usr/bin/git clone https://github.com/bling/vim-airline ~/.vim/bundle/vim-airline

# Set up vim-fugitive
/usr/bin/git clone git://github.com/tpope/vim-fugitive.git ~/.vim/bundle/vim-fugitive
