#!/bin/zsh

cp .vimrc $HOME/

pushd $HOME

# Set up Vundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

vim +PluginInstall +qall

# Set up YouCompleteMe
pushd $HOME/.vim/bundle/YouCompleteMe
./install.py --clang-completer
popd

# Set up cscope
mkdir -p $HOME/.vim/plugin

pushd $HOME/.vim/plugin
curl -LSso cscope_maps.vim http://cscope.sourceforge.net/cscope_maps.vim
popd

popd
